### ISSUE TITLE
Select2 dosnt work after update

### ISSUE THREAD

**Issue by bmikael82** [saltcorn/select2#1]
Cannot input value to search anymore, running saltcorn 0.7.0-beta.2 with 0.1.4 of select2. But problem started a couple of versions ago. Think it was with update to saltcorn 0.7.0 and previus version of select2 plugin.

**Comment by glutamate** [comment]
I see it being somewhat broken: the drop-down works and you can use it to pick a value (like a normal select drop down). But you cannot type anything in the text entry box (which is the whole point of using select2)

Is this what you also see @bmikael82 ?

**Comment by glutamate** [comment]
0.1.5 should fix this

**Comment by bmikael82** [comment]
Thank you for a quick solujtion, it workes fine after update to 0.1.5!
